version: '3.8'
services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: PB_database
    volumes:
     - fullstack-data:/var/lib/postgresql/data

  backweb:
    build:
      context: .
    volumes:
      - .:/backend
    ports:
      - 8000:8000
    image: backend:dev
    container_name: fullstack_backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
     - .env
    depends_on:
      - postgresdb

volumes:
  fullstack-data:
